### ISSUE TITLE
Pixel size of CBED patterns

### ISSUE THREAD

**Issue by shz224** [HamishGBrown/MuSTEM#26]
How can I know the pixel size of CBED patterns (`dk`) simulated by MuSTEM? For example, I divide a unit cell with lattice parameter `a` and `b` by `Nx` and `Ny` in the program, I found two ways to calculate `dk` and don't know which one is right.
1. `dk = min(1/a, 1/b)`
2. Use the does the 'Max scattering vectors' given by the program to calculate `dk`. Suppose the max scattering vectors are `k_xmax` and `k_ymax`, then `dk = min(k_xmax/Nx, k_ymax/Ny)`
The two methods give different results. Could anyone tell me the real way the program uses to determine `dk` please?

**Comment by HamishGBrown** [comment]
Hi @jshcht, pixel size is given by the reciprocal of cell size (tiling x unit cell size). If you have a rectangular grid (pixel sizes Δx and Δy are different) then you pixels in reciprocal space be rectangular (Δkx will be different to Δky)

**Comment by shz224** [comment]
Thanks!
